console.log(`------Before Swap------`);
var sweety = `Sweety`;
var cutie = `Cutie`;
console.log(`${sweety}`, `${cutie}`);
var temp = sweety;
sweety = cutie;
cutie = temp;
console.log(`------After swap-------`);
console.log(`${sweety} ${cutie}`);
console.log(`=======================`);
console.log(`------Before Swap------`);
var num1 = 1000;
var num2 = 2000;
var num3 = 3000;
console.log(`${num1} ${num2} ${num3}`);
console.log(`------After swap-------`);
var temp = num1;
num1 = num2;
num2 = num3;
num3 = temp;
console.log(`${num1} ${num2} ${num3}`);